### PR TITLE
Xcode 7 beta4 support

### PR DESCRIPTION
**Pull request by josephlord**
Hi Daniel

Couple of minor tweaks to work with Xcode7 beta 4. I'm also getting a problem of not seeing the line (I've called penDown and set a pen Color) but I haven't found that issue yet.

### CODE REVIEW

**Comment by dimsumthinking** [comment]
Thanks Joseph -

I’ve confirmed the compiler error in Beta4 and had made the same fix - I’ll use yours (i.e. init -> init?)

The left() is an error on my part - I’m torn. I want to keep angles as Ints and just have one right and one left but I think at some point people will want non-integral angles. For now I think the best fix is the one you suggest.

Best,

Daniel

**Comment by josephlord** [comment]
For left it was the ambiguity between the func left() default argument 
version of the other one that cause problems when I tried to use it. The 
Double/Int overload should be fine (no ambiguity). And you could get rid 
of the left() and right() and just have the default argument version if 
you wanted but I'm not sure it autocompletes as nicely.

**Comment by dimsumthinking** [comment]
Agreed - I’ll stick with your solution (if I can figure out how to merge it in)

**Comment by dimsumthinking** [comment]
Thank you Joseph!

**Pull request merged**
